name: Otus homework tests

on:
  push:
    branches:
      - hw*

env:
  GO111MODULE: "on"

jobs:
  go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: go get
        run: cd /tmp && go get -v "github.com/${GITHUB_REPOSITORY}/${BRANCH}@${BRANCH}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=3m ./...
        working-directory: ${{ env.BRANCH }}
